# Generated by Django 4.2 on 2023-04-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Ana səhifə banner', 'verbose_name_plural': 'Ana səhifə banner'},
        ),
    ]
