# Generated by Django 4.2 on 2023-04-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_homepage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('image', models.ImageField(upload_to='about', verbose_name='şəkil')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='BelowBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('description', models.TextField(verbose_name='mətn')),
            ],
            options={
                'verbose_name': 'Bannerin altındakı 3 yazı',
                'verbose_name_plural': 'Bannerin altındakı 3 yazı',
            },
        ),
    ]
