# Generated by Django 4.2 on 2023-04-29 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_belowbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='başlıq')),
                ('description', models.TextField(verbose_name='mətn')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.about')),
            ],
            options={
                'verbose_name': 'Haqqımızda punkt',
                'verbose_name_plural': 'Haqqımızda punktlar',
            },
        ),
    ]
