# Generated by Django 4.2 on 2023-05-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpoint',
            name='about',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.about'),
        ),
    ]
