# Generated by Django 4.2 on 2023-05-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aboutpoint_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ad soyad')),
                ('feedback', models.TextField(verbose_name='mətn')),
                ('image', models.ImageField(upload_to='clientFeedback', verbose_name='şəkil')),
            ],
            options={
                'verbose_name': 'Müştəri rəyləri',
                'verbose_name_plural': 'Müştəri rəyləri',
            },
        ),
    ]
